In [1]:
import numpy as np
import pylab as plt
import torch

In [3]:
tconv2d = torch.nn.Conv2d(1, 1, (3, 3), padding=1)

In [4]:
tconv2d.weight.detach().numpy().shape

(1, 1, 3, 3)

In [5]:
tconv2d.bias.shape

torch.Size([1])

In [6]:
state = tconv2d.state_dict()
state['weight'] = torch.tensor(np.ones(9).reshape(1,1,3,3).astype(np.float32))
state['bias'] = torch.tensor(np.zeros(1).astype(np.float32))

In [7]:
tconv2d.load_state_dict(state)

<All keys matched successfully>

In [8]:
img = np.arange(9).reshape(1,1,3,3)
iimg = torch.tensor(img).float()

In [9]:
oimg = tconv2d(iimg)

In [10]:
oimg.shape

torch.Size([1, 1, 3, 3])

In [11]:
iimg.numpy().shape

(1, 1, 3, 3)

In [12]:
iimg.numpy()

array([[[[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]]], dtype=float32)

In [13]:
oimg.detach().numpy()

array([[[[ 8., 15., 12.],
         [21., 36., 27.],
         [20., 33., 24.]]]], dtype=float32)

In [14]:
tconv2d.weight

Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)