In [1]:
import sys
sys.path.append('../repos/Hallgerd/')

In [2]:
import numpy as np

import gunnar
from gunnar.core import Device

devices = Device.getDevices()
dnames = [d for d in devices]
print('Found devices:\n\t{}'.format('\n\t'.join(dnames)))
print('\nUsing ', dnames[0])
gpu = Device([devices[dnames[0]]], DTYPE=np.float32, TS=32, TSK=32, WPTM=4, WPTN=4, TSM=128, TSN=128)

Found devices:
	GeForce GTX 660

Using  GeForce GTX 660


In [3]:
a = np.vstack((np.arange(9), np.arange(9), np.arange(9), np.arange(9))).reshape(18, 2)
b = np.ones(72).reshape(72,1)

In [4]:
a[:,0].reshape(2,3,3)

array([[[0, 2, 4],
        [6, 8, 1],
        [3, 5, 7]],

       [[0, 2, 4],
        [6, 8, 1],
        [3, 5, 7]]])

In [5]:
b[:,0].reshape(4,2,3,3)

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [6]:
ga = gpu.image(a, (3,3), (2,))
gb = gpu.image(b, (3,3), (4,2))

In [7]:
gc = ga.conv2d(gb, padding=1)

In [8]:
gc.channels

(4,)

In [9]:
c = gc.to_cpu()
c[:,0].reshape(4,3,3)

array([[[72., 72., 72.],
        [72., 72., 72.],
        [72., 72., 72.]],

       [[72., 72., 72.],
        [72., 72., 72.],
        [72., 72., 72.]],

       [[72., 72., 72.],
        [72., 72., 72.],
        [72., 72., 72.]],

       [[72., 72., 72.],
        [72., 72., 72.],
        [72., 72., 72.]]], dtype=float32)

In [10]:
dwc = gc.fconv2d(ga, padding=0)
dwc = dwc.crop(((1,4), (1,4)))
dwc.shape

(72, 1)

In [11]:
print(dwc.to_cpu()[:,0].reshape(4,2,3,3))

[[[[ 972. 1404.  900.]
   [1620. 2592. 1836.]
   [1404. 2052. 1332.]]

  [[ 972. 1404.  900.]
   [1620. 2592. 1836.]
   [1404. 2052. 1332.]]]


 [[[ 972. 1404.  900.]
   [1620. 2592. 1836.]
   [1404. 2052. 1332.]]

  [[ 972. 1404.  900.]
   [1620. 2592. 1836.]
   [1404. 2052. 1332.]]]


 [[[ 972. 1404.  900.]
   [1620. 2592. 1836.]
   [1404. 2052. 1332.]]

  [[ 972. 1404.  900.]
   [1620. 2592. 1836.]
   [1404. 2052. 1332.]]]


 [[[ 972. 1404.  900.]
   [1620. 2592. 1836.]
   [1404. 2052. 1332.]]

  [[ 972. 1404.  900.]
   [1620. 2592. 1836.]
   [1404. 2052. 1332.]]]]
